/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package randevusistemi;

/**
 *
 * @author ebrar
 */
public class HastaPanel extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HastaPanel.class.getName());

    /**
     * Creates new form HastaPanel
     */
    public HastaPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnRandevuAl = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRandevular = new javax.swing.JTable();
        btnListele = new javax.swing.JButton();
        btnIptal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Hasta Paneline Hoşgeldiniz");

        btnRandevuAl.setText("Randevu Al");
        btnRandevuAl.addActionListener(this::btnRandevuAlActionPerformed);

        tblRandevular.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Doktor", "Tarih", "Saat", "Durum"
            }
        ));
        jScrollPane1.setViewportView(tblRandevular);

        btnListele.setText("Randevuları Listele");
        btnListele.addActionListener(this::btnListeleActionPerformed);

        btnIptal.setText("Randevu İptal Et");
        btnIptal.addActionListener(this::btnIptalActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRandevuAl)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnIptal)
                        .addGap(35, 35, 35)
                        .addComponent(btnListele)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(btnRandevuAl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListele)
                    .addComponent(btnIptal))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRandevuAlActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandevuAlActionPerformed
        // TODO add your handling code here:
     RandevuAlForm form = new RandevuAlForm();
     form.setVisible(true);   
    }//GEN-LAST:event_btnRandevuAlActionPerformed

    private void btnListeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListeleActionPerformed
        // TODO add your handling code here:
        try{

    javax.swing.table.DefaultTableModel model =
    (javax.swing.table.DefaultTableModel)
    tblRandevular.getModel();

    model.setRowCount(0);

    DBConnection db = new DBConnection();
    java.sql.Connection conn = db.connect();

    String sql =
    "SELECT r.randevuID, " +
    "d.ad + ' ' + d.soyad AS doktor, " +
    "r.tarih, r.saat, r.durum " +
    "FROM Randevu r " +
    "INNER JOIN Doktor d " +
    "ON r.doktorID = d.doktorID";

    java.sql.PreparedStatement pst =
    conn.prepareStatement(sql);

    java.sql.ResultSet rs =
    pst.executeQuery();

    while(rs.next()){

        Object[] row = {

            rs.getInt("randevuID"),
            rs.getString("doktor"),
            rs.getString("tarih"),
            rs.getString("saat"),
            rs.getString("durum")
        };

        model.addRow(row);
    }

}catch(Exception e){

    e.printStackTrace();
}
    }//GEN-LAST:event_btnListeleActionPerformed

    private void btnIptalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIptalActionPerformed
        // TODO add your handling code here:
       try{

    int selectedRow = tblRandevular.getSelectedRow();

    if(selectedRow == -1){
        System.out.println("Lütfen iptal edilecek randevuyu seçin.");
        return;
    }

    int randevuID = Integer.parseInt(
        tblRandevular.getValueAt(selectedRow, 0).toString()
    );

    DBConnection db = new DBConnection();
    java.sql.Connection conn = db.connect();

    String sql = "UPDATE Randevu SET durum = ? WHERE randevuID = ?";

    java.sql.PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, "İptal");
    pst.setInt(2, randevuID);

    pst.executeUpdate();

    System.out.println("Randevu iptal edildi.");

}catch(Exception e){
    e.printStackTrace();
} 
    }//GEN-LAST:event_btnIptalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new HastaPanel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIptal;
    private javax.swing.JButton btnListele;
    private javax.swing.JButton btnRandevuAl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblRandevular;
    // End of variables declaration//GEN-END:variables
}
