/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package randevusistemi;

/**
 *
 * @author ebrar
 */
public class RandevuAlForm extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(RandevuAlForm.class.getName());

    /**
     * Creates new form RandevuAlForm
     */
    public RandevuAlForm() {
        initComponents();
        
        bolumleriGetir();
           
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbBolum = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        cmbDoktor = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtTarih = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSaat = new javax.swing.JTextField();
        btnOlustur = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Bölüm:");

        cmbBolum.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBolum.addActionListener(this::cmbBolumActionPerformed);

        jLabel2.setText("Doktor:");

        cmbDoktor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Tarih:");

        txtTarih.setText("2026-05-25");

        jLabel4.setText("Saat:");

        txtSaat.setText("10:30");

        btnOlustur.setText("Randevu Oluştur");
        btnOlustur.addActionListener(this::btnOlusturActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSaat, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtTarih, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbBolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnOlustur)))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbBolum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbDoktor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSaat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOlustur)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBolumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBolumActionPerformed
        // TODO add your handling code here:
        doktorlariGetir();
    }//GEN-LAST:event_cmbBolumActionPerformed

    private void btnOlusturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlusturActionPerformed
        // TODO add your handling code here:
        try{

    String doktor =
    cmbDoktor.getSelectedItem().toString();

    String tarih = txtTarih.getText();
    String saat = txtSaat.getText();

    DBConnection db = new DBConnection();
    java.sql.Connection conn = db.connect();

    String doktorSql =
    "SELECT doktorID FROM Doktor " +
    "WHERE ad + ' ' + soyad = ?";

    java.sql.PreparedStatement pstDoktor =
    conn.prepareStatement(doktorSql);

    pstDoktor.setString(1, doktor);

    java.sql.ResultSet rs =
    pstDoktor.executeQuery();

    int doktorID = 0;

    if(rs.next()){

        doktorID = rs.getInt("doktorID");
    }
    String kontrolSql =
"SELECT * FROM Randevu " +
"WHERE doktorID = ? AND tarih = ? " +
"AND CONVERT(VARCHAR(5), saat, 108) = ? " +
"AND durum = 'Aktif'";

java.sql.PreparedStatement pstKontrol =
conn.prepareStatement(kontrolSql);

pstKontrol.setInt(1, doktorID);
pstKontrol.setString(2, tarih);
pstKontrol.setString(3, saat);

java.sql.ResultSet rsKontrol =
pstKontrol.executeQuery();

if(rsKontrol.next()){

    System.out.println("Bu saat için zaten randevu var!");
    return;
}
    

    String sql =
    "INSERT INTO Randevu " +
    "(hastaID, doktorID, tarih, saat, durum) " +
    "VALUES (?, ?, ?, ?, ?)";

    java.sql.PreparedStatement pst =
    conn.prepareStatement(sql);

    pst.setInt(1, 1);
    pst.setInt(2, doktorID);
    pst.setString(3, tarih);
    pst.setString(4, saat);
    pst.setString(5, "Aktif");

    pst.executeUpdate();

    System.out.println("Randevu oluşturuldu!");

}catch(Exception e){

    e.printStackTrace();
}
    }//GEN-LAST:event_btnOlusturActionPerformed

    
    public void bolumleriGetir(){

    try{
        cmbBolum.removeAllItems(); 
        
        DBConnection db = new DBConnection();
        java.sql.Connection conn = db.connect();

        String sql = "SELECT bolumAdi FROM Bolum";

        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        while(rs.next()){
            cmbBolum.addItem(rs.getString("bolumAdi"));
        }

    }catch(Exception e){
        e.printStackTrace();
    }
}
    public void doktorlariGetir(){

    try{
        cmbDoktor.removeAllItems();

        if(cmbBolum.getSelectedItem() == null){
            return;
        }

        DBConnection db = new DBConnection();
        java.sql.Connection conn = db.connect();

        String bolum = cmbBolum.getSelectedItem().toString();

        String sql =
        "SELECT ad, soyad FROM Doktor d " +
        "INNER JOIN Bolum b ON d.bolumID = b.bolumID " +
        "WHERE b.bolumAdi = ?";

        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, bolum);

        java.sql.ResultSet rs = pst.executeQuery();

        while(rs.next()){
            String doktor = rs.getString("ad") + " " + rs.getString("soyad");
            cmbDoktor.addItem(doktor);
        }

    }
    catch(Exception e){
        e.printStackTrace();
    }
}
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new RandevuAlForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOlustur;
    private javax.swing.JComboBox<String> cmbBolum;
    private javax.swing.JComboBox<String> cmbDoktor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtSaat;
    private javax.swing.JTextField txtTarih;
    // End of variables declaration//GEN-END:variables
}
